SELECT * FROM TBUSER
select * from TBPROCESS


SELECT D.COMPANYNAME, E.NAME, A.DT_PROCESS, SUM(A.TOTAL) AS TOTAL, C.COMISSION , SUM((A.TOTAL /100) * C.COMISSION) AS COMISSION_VALUE
FROM TBPROCESS A
INNER JOIN TBPROCESS_ITEM B ON  A.ID_PROCESS = B.ID_PROCESS
INNER JOIN  TBPRICELIST C ON C.ID_COMPANY = A.ID_COMPANY AND B.ID_PRICELIST = C.ID_PRICELIST
INNER JOIN TBCOMPANY D ON D.ID_COMPANY = A.ID_COMPANY
INNER JOIN TBCONTRACTORS E ON E.ID_CONTRACTORS = A.ID_CONTRACTORS
WHERE A.TOTAL  > 0
--AND A.STATUS = 'Accepted'
GROUP BY A.DT_PROCESS , C.COMISSION, D.COMPANYNAME, E.NAME



select * from TBPROCESS WHERE ID_CONTRACTORS <> ID_USER

select * from TBPROCESS_ITEM
