--TRUNCATE TABLE TBADDRESS
--TRUNCATE TABLE TBCOMPANY
TRUNCATE TABLE TBCONTACT
TRUNCATE TABLE TBCONTRACTORS
TRUNCATE TABLE TBCREDITORS
TRUNCATE TABLE TBCREDITORS_PRODUCT
--TRUNCATE TABLE TBCUSTOMER
--TRUNCATE TABLE TBKEYS
--TRUNCATE TABLE TBMESSAGE
--TRUNCATE TABLE TBMISCELLANEOUS
--TRUNCATE TABLE TBPARAMETERS
--TRUNCATE TABLE TBPOSITION
TRUNCATE TABLE TBPRICEITEM
TRUNCATE TABLE TBPRICELIST
TRUNCATE TABLE TBPROCESS
TRUNCATE TABLE TBPROCESS_ITEM
--TRUNCATE TABLE TBPRODUCT
---TRUNCATE TABLE TBSUPPLIER
TRUNCATE TABLE TBTERMS
TRUNCATE TABLE TBSERVICE
TRUNCATE TABLE TBSERVICE_FOLLOWUP

--TRUNCATE TABLE TBTYPEBRAND
--TRUNCATE TABLE TBUSER
--TRUNCATE TABLE TBVENDOR_PRICINGTABLE
GO
-- TABELAS VIRTUAIS APENAS PARA CONTROLE DA CHAVE PRIMARIA
UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBMESSAGE)
WHERE TABLENAME = 'TBMESSAGE'

UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBMISCELLANEOUS)
WHERE TABLENAME = 'TBMISCELLANEOUS'

UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBPARAMETERS)
WHERE TABLENAME = 'TBPARAMETERS'

UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBPOSITION)
WHERE TABLENAME = 'TBPOSITION'

UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBTYPEBRAND)
WHERE TABLENAME = 'TBTYPEBRAND'


UPDATE TBKEYS
SET VALUE = (SELECT COUNT(1) FROM TBUSER)
WHERE TABLENAME = 'TBUSER'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBESTIMATE'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBESTIMATE_ITEM'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBORDER'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBORDER_ITEM'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBINVOICE'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBINVOICE_ITEM'

----------------------------------------------------------

DELETE FROM TBKEYS WHERE TABLENAME = 'TBADDRESS'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBCOMPANY'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBCONTACT'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBCUSTOMER'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBSUPPLIER'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPRODUCT'


DELETE FROM TBKEYS WHERE TABLENAME = 'TBCONTRACTORS'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBCREDITORS'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBCREDITORS_PRODUCT'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBKEYS'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBMESSAGE'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBMISCELLANEOUS'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBPARAMETERS'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBPOSITION'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPRICEITEM'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPRICELIST'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPROCESS'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPROCESS_ITEM'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBPRODUCT'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBTERMS'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBTYPEBRAND'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBUSER'
--DELETE FROM TBKEYS WHERE TABLENAME = 'TBVENDOR_PRICINGTABLE'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBSUP_INVOICE'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBSUP_INVOICEITEM'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBSERVICE_ITEM'
DELETE FROM TBKEYS WHERE TABLENAME = 'TBSAMPLECHECKOUT'

GO
EXEC SP_ATUALIZA_TBKEY

SELECT * FROM TBVENDOR_PRICINGTABLE

select * from TBKEYS

------------------------- APAGAR QUOTATION, ORDER, INVOICE --------------


TRUNCATE TABLE TBPROCESS
TRUNCATE TABLE TBPROCESS_ITEM
TRUNCATE TABLE TBTERMS
TRUNCATE TABLE TBSERVICE
TRUNCATE TABLE TBSUP_INVOICE
TRUNCATE TABLE TBSUP_INVOICEITEM
TRUNCATE TABLE TBREQUESTORDER

TRUNCATE TABLE TBSERVICE_ITEM
TRUNCATE TABLE TBPAYABLE
TRUNCATE TABLE TBRECEIVABLE
TRUNCATE TABLE TBSERVICE_CREW
TRUNCATE TABLE TBSERVICE_ITEM
TRUNCATE TABLE TBSAMPLECHECKOUT
TRUNCATE TABLE TBFOLLOWUP
TRUNCATE TABLE TBBANKSTATEMENT

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBSAMPLECHECKOUT'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBSERVICE_ITEM'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBPAYABLE'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBRECEIVABLE'




UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBREQUESTORDER'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBSUP_INVOICE'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBSUP_INVOICEITEM'


UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBESTIMATE'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBESTIMATE_ITEM'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBORDER'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBORDER_ITEM'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBINVOICE'

UPDATE TBKEYS
SET VALUE = 0
WHERE TABLENAME = 'TBINVOICE_ITEM'



DELETE FROM TBINVENTORY WHERE ID_INVENTORY >= 51
