CREATE TABLE TBUSER (
	ID_USER	INTEGER PRIMARY KEY IDENTITY(1,1),
	LASTNAME VARCHAR(20),
	MIDDLE_NAME VARCHAR(20),
	FIRST_NAME VARCHAR(20),
	EMAIL	VARCHAR(100) UNIQUE,
	PWD	VARCHAR(10),
	COMPUTERNAME	VARCHAR(20),
	PHONE_NUMBER	VARCHAR(12),
	ACTIVE	INTEGER,
	CREATE_DATE	DATETIME DEFAULT CURRENT_TIMESTAMP,
	ID_USERPAI	INTEGER
)

INSERT INTO TBUSER (LASTNAME, MIDDLE_NAME, FIRST_NAME, EMAIL, PWD, COMPUTERNAME, PHONE_NUMBER, ACTIVE, ID_USERPAI)
VALUES ('ADMIN', 'A', 'ADMIN', 'admin@floorsofcolumbus.com', '123','', '706-3153746', 1, 0)

select * from TBUSER

drop table TBUSER

SELECT * FROM TBMESSAGE