BEGIN TRANSACTION;

CREATE TABLE TBPARAMETERS (
	ID_PARAMETERES	INTEGER PRIMARY KEY IDENTITY(1,1),
	DESCRIPTION_VALUE	VARCHAR(10),
	DESCRIPTION_CONTENT	VARCHAR(10)
);
INSERT INTO "TBPARAMETERS" (DESCRIPTION_VALUE,DESCRIPTION_CONTENT) VALUES ('VERSION','1');
COMMIT;

drop table TBPARAMETERS

select * from TBPARAMETERS
