create table TBSUPPLIER
(
  ID_SUPPLIER INT PRIMARY KEY,
  REG_DATE DATE,
  REG_TIME TIME,
  NAMEBUSINESS VARCHAR(100),
  TRADININGNAME VARCHAR(50),
  COUNTRY VARCHAR(30),
  STATEE VARCHAR(2),
  ADDRESS1 VARCHAR(400),
  ADDRESS2 VARCHAR(400),
  PHONENUMBER VARCHAR(12),
  ZIPCODE VARCHAR(10),
  INDUSTRY VARCHAR(50),
  PRODUCT_SERVICE VARCHAR(400),
  CONTACTNAME1 VARCHAR(50),
  CONTACTEMAIL1 VARCHAR(100),
  CONTACTPOSITION1 VARCHAR(50),
  CONTACTPHONENUMBER1 VARCHAR(12),
  CONTACTNAME2 VARCHAR(50),
  CONTACTEMAIL2 VARCHAR(100),
  CONTACTPOSITION2 VARCHAR(50),
  CONTACTPHONENUMBER2 VARCHAR(12),
  WEBSITE VARCHAR(100),
  ADDITIONINFO VARCHAR(4000)
)

drop table TBSUPPLIER

CREATE TABLE TBKEYS
(
  ID_TBKEYS INT IDENTITY(1,1) PRIMARY KEY,
  TABLENAME VARCHAR(30),
  VALUE BIGINT
)

INSERT INTO TBKEYS (TABLENAME, VALUE) VALUES ('TBSUPPLIER',0)

Select Value + 1  From TBKEYS where TABLENAME = 'TBSUPPLIER'

select * from TBSUPPLIER

SELECT FORMAT(reg_time,'hh:mm tt') AS StartTime
FROM TBSUPPLIER

DECLARE @d DATETIME = '10/01/2011 13:14';
SELECT FORMAT(@d,'hh:mm tt') 

alter table TBSUPPLIER
add ID_USER int

select * from TBUSER

update TBSUPPLIER
set ID_USER = 1



